[tool.poetry]
name = "{{ repo }}"
version = "0.0.1"
description = "{{ description }}"
authors = ["{{ author }}"]

[tool.poetry.dependencies]
python = "{{ pyversion }}"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
